project_id = "xzyqcnapqfiawjmgfxws"

[functions.staff-auth]
verify_jwt = false

[functions.submit-certificate]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-registration-notification]
verify_jwt = false

[functions.send-approval-notification]
verify_jwt = false

[functions.send-name-change-notification]
verify_jwt = false
